[package]
name = "cbindgen-expand-bug"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.49"
cbindgen = "0.9.0"
